services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fast-pizza
    ports:
      - 5432:5432
    volumes:
      - fast-pizza-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: fast-pizza-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  fast-pizza-data:
